# Generated by Django 5.2.7 on 2025-10-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_name', models.CharField(max_length=100, null=True)),
                ('order_product', models.CharField(max_length=100)),
                ('order_quantity', models.IntegerField()),
                ('order_date', models.DateField()),
            ],
        ),
    ]
